name: NAClib Actions
run-name: ${{ github.actor }} is testing out Sphinx-build on GitHub Actions 🚀
on: [push]
permissions:
  contents: write
jobs:
  Generate-Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install jinja2==2.11.2
          pip install markupsafe==1.1.1
          pip install sphinx==3.1.2
          pip install sphinx-rtd-theme==1.0.0
      - name: Build docs
        run: |
          sphinx-build -b html docs/source docs/build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
